"""A small gallery of classic path fractals animated order by order."""

from __future__ import annotations

import argparse
from math import atan2, cos, sin, sqrt
from pathlib import Path
from typing import Callable, NamedTuple

from zanim import (
    CYAN,
    GREEN,
    MUTED,
    ORANGE,
    PINK,
    TAU,
    WHITE,
    YELLOW,
    Canvas,
    Color,
    Polyline,
    Scene,
    Text,
    Vec2,
)

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "media/extras/fractals.mp4"

SIDE = 7.0
CREATE_DURATION = 0.65
TRANSITION_DURATION = 0.78
ORDER_HOLD = 0.16
SECTION_HOLD = 0.38
FADE_DURATION = 0.32


def _as_vec2(points: list[complex]) -> tuple[Vec2, ...]:
    return tuple(Vec2(point.real, point.imag) for point in points)


def orient_endpoint_chord(points: tuple[Vec2, ...], *, angle: float = 0.0) -> tuple[Vec2, ...]:
    """Rotate an open path so its start-to-end chord has one canonical angle."""
    if len(points) < 2:
        raise ValueError("path requires at least two points")
    source = complex(points[-1].x - points[0].x, points[-1].y - points[0].y)
    if abs(source) <= 1e-12:
        raise ValueError("path endpoints must differ to define an orientation")
    rotation = angle - atan2(source.imag, source.real)
    unit = complex(cos(rotation), sin(rotation))
    return tuple(
        Vec2((complex(point.x, point.y) * unit).real, (complex(point.x, point.y) * unit).imag)
        for point in points
    )


def fit_points(points: tuple[Vec2, ...], *, side: float = SIDE) -> tuple[Vec2, ...]:
    """Center and uniformly scale a path into a square authoring region."""
    if len(points) < 2:
        raise ValueError("path requires at least two points")
    if side <= 0:
        raise ValueError("side must be positive")
    x0 = min(point.x for point in points)
    x1 = max(point.x for point in points)
    y0 = min(point.y for point in points)
    y1 = max(point.y for point in points)
    width = x1 - x0
    height = y1 - y0
    extent = max(width, height)
    if extent <= 1e-12:
        raise ValueError("cannot fit a zero-size path")
    scale = side / extent
    cx = (x0 + x1) * 0.5
    cy = (y0 + y1) * 0.5
    return tuple(Vec2((point.x - cx) * scale, (point.y - cy) * scale) for point in points)


def koch_snowflake_points(order: int, *, side: float = SIDE) -> tuple[Vec2, ...]:
    """Closed Koch snowflake boundary, starting from an equilateral triangle."""
    if order < 0:
        raise ValueError("Koch order must be >= 0")
    h = sqrt(3.0) / 2.0
    points = [complex(-0.5, -h / 3), complex(0.5, -h / 3), complex(0.0, 2 * h / 3)]
    points.append(points[0])
    outward_turn = complex(cos(-TAU / 6), sin(-TAU / 6))

    for _ in range(order):
        refined: list[complex] = []
        for a, b in zip(points, points[1:]):
            delta = (b - a) / 3.0
            p1 = a + delta
            p2 = p1 + delta * outward_turn
            p3 = a + 2.0 * delta
            refined.extend((a, p1, p2, p3))
        refined.append(points[-1])
        points = refined
    return fit_points(_as_vec2(points), side=side)


def sierpinski_arrowhead_points(order: int, *, side: float = SIDE) -> tuple[Vec2, ...]:
    """Sierpiński arrowhead curve generated by its two-symbol L-system."""
    if order < 0:
        raise ValueError("Sierpiński order must be >= 0")
    word = "A"
    for _ in range(order):
        word = "".join(
            "B-A-B" if token == "A" else "A+B+A" if token == "B" else token for token in word
        )

    angle = 0.0
    turn = TAU / 6.0
    position = complex(0.0, 0.0)
    points = [position]
    for token in word:
        if token in "AB":
            position += complex(cos(angle), sin(angle))
            points.append(position)
        elif token == "+":
            angle += turn
        elif token == "-":
            angle -= turn
    # Odd/even arrowhead orders leave the traversal chord at different angles.
    # Canonicalize that global pose before fitting so animation emphasizes the
    # recursive detail instead of an incidental 60° whole-curve rotation.
    oriented = orient_endpoint_chord(_as_vec2(points))
    return fit_points(oriented, side=side)


def dragon_curve_points(order: int, *, side: float = SIDE) -> tuple[Vec2, ...]:
    """Heighway dragon generated by repeatedly folding a polyline by 90 degrees."""
    if order < 0:
        raise ValueError("Dragon order must be >= 0")
    points = [complex(0.0, 0.0), complex(1.0, 0.0)]
    for _ in range(order):
        pivot = points[-1]
        points.extend(pivot + (point - pivot) * 1j for point in reversed(points[:-1]))
    # The raw folding construction rotates its endpoint chord by 45° per order.
    # Keep the chord horizontal across orders; the dragon itself still unfolds
    # naturally, but no longer spins as a whole during a morph.
    oriented = orient_endpoint_chord(_as_vec2(points))
    return fit_points(oriented, side=side)


def levy_c_points(order: int, *, side: float = SIDE) -> tuple[Vec2, ...]:
    """Lévy C curve, replacing each segment with two 45-degree branches."""
    if order < 0:
        raise ValueError("Lévy order must be >= 0")
    points = [complex(-0.5, 0.0), complex(0.5, 0.0)]
    for _ in range(order):
        refined: list[complex] = []
        for a, b in zip(points, points[1:]):
            apex = (a + b) * 0.5 + (b - a) * 0.5j
            refined.extend((a, apex))
        refined.append(points[-1])
        points = refined
    return fit_points(_as_vec2(points), side=side)


class FractalSpec(NamedTuple):
    name: str
    subtitle: str
    generator: Callable[[int], tuple[Vec2, ...]]
    first_order: int
    last_order: int
    color: Color


FRACTALS = (
    FractalSpec(
        "Koch snowflake",
        "each edge becomes four self-similar edges",
        koch_snowflake_points,
        0,
        5,
        CYAN,
    ),
    FractalSpec(
        "Sierpiński arrowhead",
        "one continuous curve approaches the Sierpiński triangle",
        sierpinski_arrowhead_points,
        1,
        7,
        GREEN,
    ),
    FractalSpec(
        "Heighway dragon",
        "fold, rotate 90°, and repeat",
        dragon_curve_points,
        1,
        12,
        PINK,
    ),
    FractalSpec(
        "Lévy C curve",
        "every segment becomes two 45° branches",
        levy_c_points,
        0,
        11,
        ORANGE,
    ),
)


def _curve(spec: FractalSpec, order: int, *, trim: float = 1.0) -> Polyline:
    return Polyline(
        spec.generator(order),
        stroke=spec.color,
        stroke_width=max(0.018, 0.052 - 0.003 * max(0, order - spec.first_order)),
        trim=trim,
        z_index=1,
    )


def _heading(spec: FractalSpec) -> tuple[Text, Text]:
    title = Text(spec.name, font_size=35, color=WHITE, opacity=0, z_index=10)
    subtitle = Text(spec.subtitle, font_size=19, color=MUTED, opacity=0, z_index=10)
    title.move_to((0, 4.25))
    subtitle.move_to((0, 3.78))
    return title, subtitle


def _order_label(order: int, point_count: int) -> Text:
    label = Text(
        f"order {order}   ·   {point_count - 1:,} segments",
        font_size=20,
        color=YELLOW,
        opacity=0,
        z_index=10,
    )
    label.move_to((0, -4.28))
    return label


def _animate_fractal(scene: Scene, spec: FractalSpec) -> None:
    first_points = spec.generator(spec.first_order)
    first = _curve(spec, spec.first_order, trim=0.0)
    title, subtitle = _heading(spec)
    label = _order_label(spec.first_order, len(first_points))

    curve, title, subtitle, label = scene.add(first, title, subtitle, label)
    with scene.parallel():
        curve.create(duration=CREATE_DURATION)
        title.fade_in(duration=0.42)
        subtitle.fade_in(duration=0.48, at=0.08)
        label.fade_in(duration=0.42, at=0.08)
    scene.wait(SECTION_HOLD)

    for order in range(spec.first_order + 1, spec.last_order + 1):
        next_curve = _curve(spec, order)
        next_points = spec.generator(order)
        curve = scene.replace(curve, next_curve, duration=TRANSITION_DURATION)

        next_label = scene.add(_order_label(order, len(next_points)))
        with scene.parallel(duration=0.16):
            label.fade_out()
            next_label.fade_in()
        label.remove()
        label = next_label
        scene.wait(ORDER_HOLD)

    scene.wait(SECTION_HOLD)
    with scene.parallel(duration=FADE_DURATION):
        curve.fade_out()
        title.fade_out()
        subtitle.fade_out()
        label.fade_out()
    curve.remove()
    title.remove()
    subtitle.remove()
    label.remove()


def _build_scene(*, section: str | None = None) -> Scene:
    scene = Scene(canvas=Canvas(width=1280, height=960, unit_size=100), fps=60)
    specs = FRACTALS
    if section is not None:
        key = section.casefold()
        specs = tuple(spec for spec in FRACTALS if key in spec.name.casefold())
        if not specs:
            names = ", ".join(spec.name for spec in FRACTALS)
            raise ValueError(f"unknown fractal section {section!r}; choose from: {names}")

    for spec in specs:
        _animate_fractal(scene, spec)
    scene.wait(0.35)
    return scene


def build_scene() -> Scene:
    """Default gallery used by ``zanim preview/render``."""
    return _build_scene()


def main() -> None:
    parser = argparse.ArgumentParser(description="Animate several classic fractals in one scene")
    parser.add_argument(
        "--section",
        default=None,
        help="render one matching section, e.g. koch, sierpiński, dragon, or lévy",
    )
    parser.add_argument("--output", type=Path, default=OUTPUT)
    args = parser.parse_args()

    scene = _build_scene(section=args.section)
    output = scene.render_video(
        args.output,
        fps=60,
        workers=8,
        verify_random_access=True,
    )
    print(output)
    print(
        f"duration={scene.duration:.2f}s sections={len(FRACTALS) if args.section is None else 1} random-access=ok"
    )


if __name__ == "__main__":
    main()
